version: "1.0"
# Stages can help you organize your steps in stages
stages:
  - "clone"
  - "prepare"
  - "plan"
  - "deploy"

steps:
  clone:
    title: "Cloning repository"
    type: "git-clone"
    repo: "VaishnaviV1105/pipelinerepo"
    # CF_BRANCH value is auto set when pipeline is triggered
    # Learn more at codefresh.io/docs/docs/codefresh-yaml/variables/
    revision: "${{CF_BRANCH}}"
    git: "github"
    stage: "clone"

  SetupAuth:
    image: alpine:3.9
    title: Setting up aws auth
    stage: prepare
    commands:
      - cf_export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - cf_export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

  plan:
    title: Terraform Plan
    type: freestyle
    working_directory: './pipelinerepo'
    arguments:
      image: 'hashicorp/terraform'
      commands:
        - terraform init
        - terraform validate
        - terraform plan
    stage: plan

  deploy:
    title: Terraform Apply
    type: freestyle
    working_directory: './pipelinerepo'
    arguments:
      image: 'hashicorp/terraform'
      commands:
        - terraform init
        - terraform apply -auto-approve
    stage: "deploy"